name       : python-cachecontrol
version    : 0.12.13
release    : 2
source     :
    - https://github.com/psf/cachecontrol/archive/refs/tags/v0.12.13.tar.gz : d9987916bbb701ddfd937c70bde99440e73f5bba28e3fd816596e91fc3b4208d
license    : Apache-2.0
component  : programming.python
summary    : The httplib2 caching algorithms packaged up for use with requests.
description: |
    CacheControl is a port of the caching algorithms in httplib2 for use with requests session object. It was written because httplib2's better support for caching is often mitigated by its lack of thread safety. The same is true of requests in terms of caching.
rundeps    :
    - python-msgpack
    - python-requests
build      : |
    %python3_setup
install    : |
    %python3_install
